### ISSUE TITLE
Delete email

### ISSUE THREAD

**Issue by sad270** [nodemailer/nodemailer-app#1]
i use NodemailApp as Fake SMTP server for development on Symfony Project.
It's working good. But we can not delete emails, and i have lot's of emails
Need delete email feature and clear inbox feature please :)

- NodemailApp 1.0.11
- MacOS Catalina 10.15.1 (19B88)

Thanks !

**Comment by andris9** [comment]
Flushing all emails in a project is planned into next release (but not deleting individual emails).

**Comment by andris9** [comment]
NodemailerApp 1.0.12 now has an option to flush all messages in active project. Upgrades are processed automatically in OSX so if your app has been open for some time you should get the newer version installed after restarting the app. Check NodemailerApp->About NodemailerApp menu item to see which version you are currently using.

<img width="577" alt="Screenshot 2019-12-11 at 12 46 55" src="https://user-images.githubusercontent.com/132242/70615131-7b31b400-1c14-11ea-9762-cac8d9a3508b.png">

**Comment by sad270** [comment]
I really need this feature look at my server :
<img width="409" alt="Capture d’écran 2019-12-11 à 15 42 05" src="https://user-images.githubusercontent.com/5607440/70631044-da9bbe00-1c2c-11ea-881c-4d0e7c177b58.png">
I will update Nodemailer now to flush all messages :)
Thanks
